#!/usr/bin/env python3
"""Rasterize the firmware's 1-bpp bitmap fonts from open-source font files.

fonts.toml, next to this script, lists the pinned font sources, the faces with
their rasterization settings and the strikes written to each Rust atlas, so
tuning a font only needs a TOML change. Glyph order comes from src/charset.rs.

Needs Python 3.11+, Pillow and fontTools. The `fonts` GitHub workflow installs
them, runs this script and uploads the regenerated atlases. An optional
argument writes the atlases under another root directory.
"""

import functools
import io
import math
import re
import sys
import tomllib
import urllib.request
import zipfile
from pathlib import Path

from fontTools.ttLib import TTFont
from PIL import Image, ImageDraw, ImageFont

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
CONFIG = HERE / "fonts.toml"
CHARSET = REPO / "src" / "charset.rs"

# Outlines are measured, and "outline" faces drawn, at this multiple of the
# strike size, where hinting moves an edge by a negligible fraction of a pixel.
SCALE = 16

RENDER_MODES = ("mono", "gray", "outline")
FACE_KEYS = {"source", "axes", "render", "threshold", "tracking"}
STRIKE_KEYS = {"name", "face", "px", "cap", "line_height"}

# Stand-ins for characters a font lacks, tried before the "?" fallback.
SUBSTITUTES = {"\u00a0": " ", "\u00ad": "-", "\u00b5": "\u03bc"}

HEADER = """\
//! {title}
//!
//! Generated by scripts/fonts/generate.py from scripts/fonts/fonts.toml; do
//! not edit by hand. Glyph order follows src/charset.rs. Source fonts are not
//! distributed with this repository; see docs/licenses/FONT_NOTICES.md.

{imports}

"""


def fail(message):
    sys.exit(f"generate.py: {message}")


def charset():
    """Glyph order of src/charset.rs: printable ASCII, Latin-1, then EXTRAS."""
    source = CHARSET.read_text(encoding="utf-8")
    found = re.search(r"const EXTRAS: \[char; (\d+)\] = \[(.*?)\];", source, re.S)
    if found is None:
        fail(f"no EXTRAS array in {CHARSET}")
    extras = re.findall(r"'(.)'", found.group(2))
    if len(extras) != int(found.group(1)):
        fail(f"read {len(extras)} of {found.group(1)} EXTRAS in {CHARSET}")
    printable = [chr(code) for code in range(0x20, 0x7F)]
    latin1 = [chr(code) for code in range(0xA0, 0x100)]
    return printable + latin1 + extras


def download(source):
    """Font bytes from a URL, or from one member of a zip archive at a URL."""
    url = source if isinstance(source, str) else source["url"]
    with urllib.request.urlopen(url) as response:
        data = response.read()
    if isinstance(source, str):
        return data
    return zipfile.ZipFile(io.BytesIO(data)).read(source["member"])


def round_half_up(value):
    return math.floor(value + 0.5)


def draw(font, character, mode, scale):
    """Grayscale image of `character` and the pen origin inside it.

    The image spans whole output pixels of `scale` drawn pixels each, plus a
    one-pixel margin; the origin is given in output pixels.
    """
    left, top, right, bottom = font.getbbox(character, mode=mode, anchor="ls")
    x0 = math.floor(left / scale) - 1
    y0 = math.floor(top / scale) - 1
    x1 = math.ceil(right / scale) + 1
    y1 = math.ceil(bottom / scale) + 1
    image = Image.new("L", ((x1 - x0) * scale, (y1 - y0) * scale), 0)
    canvas = ImageDraw.Draw(image)
    canvas.fontmode = mode
    canvas.text((-x0 * scale, -y0 * scale), character, font=font, fill=255, anchor="ls")
    return image, (-x0, -y0)


def cut(image, threshold):
    """1-bit image of the pixels whose coverage reaches `threshold`.

    The darkest pixel always survives, so small marks never vanish.
    """
    level = max(1, min(threshold, image.getextrema()[1]))
    return image.point(lambda value: 255 if value >= level else 0, "1")


def pack(image):
    """Rows of a 1-bit image, eight pixels per byte, most significant bit first."""
    width, height = image.size
    rows = bytearray()
    for y in range(height):
        for column in range(0, width, 8):
            value = 0
            for bit in range(min(8, width - column)):
                if image.getpixel((column + bit, y)):
                    value |= 0x80 >> bit
            rows.append(value)
    return bytes(rows)


class Face:
    """A source font with its variation axes and rasterization settings."""

    def __init__(self, name, settings, data):
        unknown = set(settings) - FACE_KEYS
        if unknown:
            fail(f"face {name}: unknown keys {sorted(unknown)}")
        self.data = data
        self.axes = settings.get("axes", {})
        self.render = settings.get("render", "mono")
        self.threshold = settings.get("threshold", 128)
        self.tracking = settings.get("tracking", 0)
        if self.render not in RENDER_MODES:
            fail(f"face {name}: render must be one of {', '.join(RENDER_MODES)}")
        if not 1 <= self.threshold <= 255:
            fail(f"face {name}: threshold must be 1-255")
        font = TTFont(io.BytesIO(data))
        self.coverage = set(font.getBestCmap())
        if self.axes and "fvar" not in font:
            fail(f"face {name}: axes are set but the font has no variations")
        self.fvar = font["fvar"].axes if self.axes else []
        unknown = set(self.axes) - {axis.axisTag for axis in self.fvar}
        if unknown:
            fail(f"face {name}: the font has no axes {sorted(unknown)}")

    def has(self, character):
        return len(character) == 1 and ord(character) in self.coverage

    def font(self, pixels, optical):
        """Pillow font at `pixels`; an axis set to "size" follows `optical`."""
        font = ImageFont.truetype(io.BytesIO(self.data), pixels)
        if self.fvar:
            values = []
            for axis in self.fvar:
                value = self.axes.get(axis.axisTag, axis.defaultValue)
                if value == "size":
                    value = optical
                values.append(min(max(value, axis.minValue), axis.maxValue))
            font.set_variation_by_axes(values)
        return font


class Strike:
    """One face rasterized at one pixel size."""

    def __init__(self, face, pixels):
        self.face = face
        self.pixels = pixels
        self.small = face.font(pixels, pixels)

    @functools.cached_property
    def large(self):
        return self.face.font(self.pixels * SCALE, self.pixels)

    def glyph(self, character):
        """(width, height, advance, left, top, rows) of one glyph."""
        face = self.face
        advance = round_half_up(self.large.getlength(character) / SCALE + face.tracking)
        outline, outline_origin = draw(self.large, character, "L", SCALE)
        ink = outline.getbbox()
        if ink is None:
            return (0, 0, advance, 0, 0, b"")
        if face.render == "outline":
            image = cut(outline.reduce(SCALE), face.threshold)
            origin = outline_origin
        elif face.render == "gray":
            image, origin = draw(self.small, character, "L", 1)
            image = cut(image, face.threshold)
        else:
            image, origin = draw(self.small, character, "1", 1)
            image = cut(image, 128)
        box = image.getbbox()
        if box is None:
            return (0, 0, advance, 0, 0, b"")
        image = image.crop(box)
        width, height = image.size
        # Hinting shifts glyphs sideways by up to a pixel and leaves uneven gaps
        # between letters, so every bitmap is centred on its unhinted outline.
        centre = (ink[0] + ink[2]) / (2 * SCALE) - outline_origin[0]
        left = round_half_up(centre - width / 2)
        return (width, height, advance, left, box[1] - origin[1], pack(image))


def strike_for(entry, face):
    """The strike an entry asks for: its pixel size, or the smallest size whose
    capital H is `cap` pixels tall (the closest size if none is exact)."""
    if "px" in entry:
        return Strike(face, entry["px"])
    best, best_error = None, None
    for pixels in range(8, 64):
        strike = Strike(face, pixels)
        error = abs(strike.glyph("H")[1] - entry["cap"])
        if error == 0:
            return strike
        if best is None or error < best_error:
            best, best_error = strike, error
    return best


def build(entry, faces, characters):
    """Rust source and a one-line summary of one strike."""
    name = entry.get("name")
    unknown = set(entry) - STRIKE_KEYS
    if unknown:
        fail(f"strike {name}: unknown keys {sorted(unknown)}")
    if ("px" in entry) == ("cap" in entry):
        fail(f"strike {name}: set exactly one of px and cap")
    face = faces.get(entry.get("face"))
    if face is None:
        fail(f"strike {name}: unknown face {entry.get('face')!r}")
    strike = strike_for(entry, face)
    fallback = strike.glyph("?")
    glyphs, bitmap, notes = [], bytearray(), []
    for character in characters:
        substitute = SUBSTITUTES.get(character, "")
        if face.has(character):
            glyph = strike.glyph(character)
        elif face.has(substitute):
            glyph = strike.glyph(substitute)
            notes.append(f"U+{ord(character):04X} as U+{ord(substitute):04X}")
        else:
            glyph = fallback
            notes.append(f"U+{ord(character):04X} missing")
        width, height, advance, left, top, rows = glyph
        glyphs.append((len(bitmap), width, height, advance, left, top))
        bitmap.extend(rows)
    render = face.render if face.render == "mono" else f"{face.render} {face.threshold}"
    summary = (
        f"{name}: {strike.pixels} px, cap {strike.glyph('H')[1]}, "
        f"line height {entry['line_height']}, {render}"
    )
    if face.tracking:
        summary += f", tracking {face.tracking}"
    if notes:
        summary += ", " + ", ".join(notes)
    return summary, emit(name, glyphs, bitmap, entry["line_height"], summary)


def emit(name, glyphs, bitmap, line_height, summary):
    lines = [
        f"// {summary}",
        f"pub static {name}: BitmapFont = BitmapFont {{",
        "    glyphs: &[",
    ]
    for glyph in glyphs:
        lines.append("        Glyph::new({}, {}, {}, {}, {}, {}),".format(*glyph))
    lines.append("    ],")
    lines.append("    bitmap: &[")
    for start in range(0, len(bitmap), 20):
        chunk = ", ".join(f"0x{byte:02X}" for byte in bitmap[start : start + 20])
        lines.append(f"        {chunk},")
    lines.extend(["    ],", f"    line_height: {line_height},", "};"])
    return "\n".join(lines)


def main():
    config = tomllib.loads(CONFIG.read_text(encoding="utf-8"))
    root = Path(sys.argv[1]) if len(sys.argv) > 1 else REPO
    characters = charset()
    downloads, faces = {}, {}
    for name, settings in config["faces"].items():
        source = settings.get("source")
        if source not in config["sources"]:
            fail(f"face {name}: unknown source {source!r}")
        if source not in downloads:
            downloads[source] = download(config["sources"][source])
        faces[name] = Face(name, settings, downloads[source])
    for output in config["outputs"]:
        blocks = []
        for entry in output["strikes"]:
            summary, block = build(entry, faces, characters)
            print(summary, flush=True)
            blocks.append(block)
        header = HEADER.format(title=output["title"], imports=output["imports"])
        target = root / output["path"]
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(header + "\n\n".join(blocks) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
